### ISSUE TITLE
programming with tensorflow and OpenFOAM

### ISSUE THREAD

**Issue by waynezw0618** [el1995/CPU-Inference-Thesis#1]
Dear Sir
 I have noticed that you are trying to programing in tensorflow together with OpenFOAM. which is very Interesting for me. I am also looking forward to carry out some similar work. would you please give some brief on how to doing so with parallel running. I would like to run both in parallel. I haven't got an idea to doing so. can you please give me some suggestion?

Yours Sincerely 
Wei

**Comment by el1995** [comment]
Dear @waynezw0618,

as you can see my thesis uses TensorFlow's C API only to perform the inference on a frozen graph (although I recommend OpenVINO). TensorFlow parallelizes the inference automatically (if you do not explicitely avoid this, as also shown in my code), the parallelization with OpenFOAM is purely MPI-based (standard). 

If you have any concrete questions regarding the implementation, feel free to reopen and ask. Otherwise, you will find the code line-by-line in the appendix of the thesis.
